[package]
name = "xpg"
version = "0.17.1"
edition = "2021"
description = "xkcd-style password generator"
repository = "https://github.com/qtfkwk/xpg"
license = "MIT"
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive", "wrap_help"] }
convert_case = { version = "0.6.0", features = ["random"] }
directories = "5.0.1"
rand = "0.8.5"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
ucfirst = "0.2.2"

[target.'cfg(unix)'.dependencies]
pager = "0.16.1"
