[package]
name = "xpg"
version = "0.17.2"
edition = "2021"
description = "xkcd-style password generator"
repository = "https://github.com/qtfkwk/xpg"
license = "MIT"
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive", "wrap_help"] }
clap-cargo = "0.14.1"
convert_case = { version = "0.6.0", features = ["random"] }
directories = "5.0.1"
rand = "0.8.5"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
ucfirst = "0.2.2"

[target.'cfg(unix)'.dependencies]
pager = "0.16.1"
