[package]
name = "xpg"
version = "0.10.0"
edition = "2021"
description = "xkcd-style password generator"
repository = "https://github.com/qtfkwk/xpg"
license = "MIT"
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.9", features = ["derive", "wrap_help"] }
directories = "5.0.1"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
ucfirst = "0.1.0"
